// <auto-generated />
using System;
using LockAi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LockAi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250717223511_AddTipoUsuario")]
    partial class AddTipoUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LockAi.Models.RepresentanteLegal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RepresentanteLegal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cpf = "12345678901",
                            Email = "mariana.alves@example.com",
                            Nome = "Mariana Alves",
                            Telefone = "11912345678"
                        },
                        new
                        {
                            Id = 2,
                            Cpf = "98765432100",
                            Email = "carlos.henrique@example.com",
                            Nome = "Carlos Henrique",
                            Telefone = "21998765432"
                        },
                        new
                        {
                            Id = 3,
                            Cpf = "45678912333",
                            Email = "fernanda.costa@example.com",
                            Nome = "Fernanda Costa",
                            Telefone = "31934567890"
                        });
                });

            modelBuilder.Entity("LockAi.Models.TipoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposUsuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Usuario"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Gestor"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Financeiro"
                        });
                });

            modelBuilder.Entity("LockAi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DtNascimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtSituacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdUsuarioSituacao")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RepresentanteLegalId")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RepresentanteLegalId");

                    b.HasIndex("TipoUsuarioId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cpf = "46284605874",
                            DtNascimento = new DateTime(2006, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DtSituacao = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "adm@gmail.com",
                            IdUsuarioSituacao = 1,
                            Login = "ADM",
                            Nome = "Admin",
                            Senha = "*123456HAS*",
                            Situacao = 1,
                            Telefone = "11971949976",
                            TipoUsuarioId = 2
                        },
                        new
                        {
                            Id = 3,
                            Cpf = "12345678900",
                            DtNascimento = new DateTime(2010, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DtSituacao = new DateTime(2025, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "joao.silva@example.com",
                            IdUsuarioSituacao = 1,
                            Login = "joaos",
                            Nome = "João Silva",
                            RepresentanteLegalId = 1,
                            Senha = "*senha123*",
                            Situacao = 1,
                            Telefone = "11987654321",
                            TipoUsuarioId = 1
                        });
                });

            modelBuilder.Entity("LockAi.Models.UsuarioImagem", b =>
                {
                    b.Property<int>("IdImagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImagem"));

                    b.Property<string>("EndImagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("IdImagem");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioImagens");
                });

            modelBuilder.Entity("LockAi.Models.Usuario", b =>
                {
                    b.HasOne("LockAi.Models.RepresentanteLegal", "RepresentanteLegal")
                        .WithMany("Usuarios")
                        .HasForeignKey("RepresentanteLegalId");

                    b.HasOne("LockAi.Models.TipoUsuario", "TipoUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("TipoUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepresentanteLegal");

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("LockAi.Models.UsuarioImagem", b =>
                {
                    b.HasOne("LockAi.Models.Usuario", null)
                        .WithMany("Imagens")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("LockAi.Models.RepresentanteLegal", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("LockAi.Models.TipoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("LockAi.Models.Usuario", b =>
                {
                    b.Navigation("Imagens");
                });
#pragma warning restore 612, 618
        }
    }
}
